name: Format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    build:
      name: Sort imports
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Sort the imports
          uses: isort/isort-action@v1.1.1
          with:
            sort-paths: src/
            requirements-files: "requirements.txt"
    autopep8:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: autopep8
          uses: peter-evans/autopep8@v2
          with:
            args: --recursive --in-place --aggressive --aggressive src/